# Generated by Django 5.1 on 2024-11-20 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_likers_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likers',
        ),
    ]
